version: "3.8"

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

  ai-service:
    build: ./ai-service
    ports:
      - "8000:8000"
    env_file:
      - ./ai-service/.env

  mongo:
    image: mongo
    ports:
      - "27017:27017"